### ISSUE TITLE
Do not use /tmp/chip nor /tmp/ready

### ISSUE THREAD

**Issue by syphernl** [katzgrau/chip#1]
Using chip simultaneous (e.g. 2 shell users) causes issues like:

```
touch: cannot touch `/tmp/chip': Permission denied
touch: cannot touch `/tmp/ready': Permission denied
```

Isn't it better to use random filenames/prefixes instead of hardcoded ones?

**Comment by katzgrau** [comment]
Great point. This is def a priority. I should be able to get some time later in the day to add it, but a pull request (if you're interested) would be extremely appreciated

## 

Kenny Katzgrau
Web: http://codefury.net
Twitter: @_kennyk_
Skype: kenny.katzgrau
