### ISSUE TITLE
Chip crashes when using invalid colors

### ISSUE THREAD

**Issue by syphernl** [katzgrau/chip#2]
Since there is no documentation (that I know off) describing all available colors we've been trying to figure out which ones work and which ones wont. 

Either way, if you put in a wrong color (e.g. "grey", "brown") Chip crashes. Perhaps its better to catch those errors and simply show it in the default color instead?

**Comment by katzgrau** [comment]
True. It's actually directly based on the perl ANSIColor module 

http://perldoc.perl.org/Term/ANSIColor.html

But definitely an error worth catching.  

## 

Kenny Katzgrau
Web: http://codefury.net
Twitter: @_kennyk_
Skype: kenny.katzgrau
