### ISSUE TITLE
Load hosts from file

### ISSUE THREAD

**Issue by syphernl** [katzgrau/chip#3]
It would be nice if Chip could load hosts from a file (one per line), instead of having to write a wrapper script for this.

**Comment by katzgrau** [comment]
Usually I use a bash alias, but are you thinking something like a .chiprc?

## 

Kenny Katzgrau
Web: http://codefury.net
Twitter: @_kennyk_
Skype: kenny.katzgrau

**Comment by syphernl** [comment]
We have a several lists with servers which regularly expands or changes, maintaining it as a bash alias does not work in our case. 

It should be a replacement for host:logfile somehow, by providing the logfile once and a single list with hosts.
